package com.example.freshdesk.api.models

data class ReportByAgentsItem(
    val assessmentInProgressGet: Int,
    val assessmentInProgressSet: Int,
    val assessmentSentGet: Int,
    val assessmentSentSet: Int,
    val awaitGet: Int,
    val awaitSet: Int,
    val awaitStatic: Int,
    val awaitingEvaluationGet: Int,
    val awaitingEvaluationSet: Int,
    val closed: Int,
    val feedbackFromTheClientGet: Int,
    val feedbackFromTheClientSet: Int,
    val inTheQueueForDeliveryGet: Int,
    val inTheQueueForDeliverySet: Int,
    val inWorkGet: Int,
    val inWorkSet: Int,
    val name: String,
    val openGet: Int,
    val openSet: Int,
    val openStatic: Int,
    val orderConfirmedGet: Int,
    val orderConfirmedSet: Int,
    val reject: Int,
    val resolvedGet: Int,
    val resolvedSet: Int,
    val submittedForVerificationGet: Int,
    val submittedForVerificationSet: Int
)